# Generated by Django 5.1.4 on 2026-09-09 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('orden_prioridad_escalada', 'Prioridad de orden escalada'), ('orden_liberada', 'Orden liberada a la bolsa'), ('orden_asignada', 'Orden asignada'), ('orden_tomada', 'Orden tomada de la bolsa'), ('orden_pendiente', 'Orden pendiente / vencida'), ('poliza_mantenimiento_proximo', 'Mantenimiento de póliza próximo')], max_length=40)),
                ('titulo', models.CharField(max_length=160)),
                ('cuerpo', models.CharField(blank=True, default='', max_length=400)),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('ref_tipo', models.CharField(blank=True, default='', max_length=20)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('clave_dedupe', models.CharField(blank=True, default='', max_length=160)),
                ('leida_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['destinatario', 'leida_at', '-created_at'], name='notificacio_destina_c68b1c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clave_dedupe__gt', '')), fields=('destinatario', 'clave_dedupe'), name='notif_dedupe_por_usuario')],
            },
        ),
    ]
