"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os  # Import os module
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

"""Security & environment"""
# Allow overriding via DEBUG env, otherwise auto-detect Render (DEBUG False on Render)
SECRET_KEY = os.environ.get('SECRET_KEY', default='your secret key')

# SECRET_KEY from env; in production it must be set
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ["*"]

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Mis apps
    "apps.common",
    "apps.nomina",
    "apps.programacion",
    "apps.taller",
    "apps.users",
    "apps.viajes",

    # Django REST Framework
    "rest_framework",
    "corsheaders",
]

# Evitar duplicados accidentales en INSTALLED_APPS (mantiene el primer orden)
INSTALLED_APPS = list(dict.fromkeys(INSTALLED_APPS))

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

MIDDLEWARE = [
    "config.middleware.RootRedirectMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "config.api_no_cache_middleware.ApiNoCacheMiddleware",
] + MIDDLEWARE

# Permitir conexión desde frontend
# Use explicit allowed origins for the Vite dev server(s) and enable credentials
# IMPORTANT: If your frontend uses session authentication you must include credentials:
# fetch(url, { method, credentials: 'include', ... })
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://192.168.56.1:3000",
    "http://192.168.0.126:3000",
    "http://10.0.0.5:3000",
    "http://10.0.0.6:3000",
    "http://10.0.0.14:3000",
    # Render frontend (production)
    "https://transportista-frontend.onrender.com",
]

# Allow cookies / session auth to be sent (frontend must use credentials: 'include')
CORS_ALLOW_CREDENTIALS = True

# Cache CORS preflight (OPTIONS) responses to reduce repeated preflight requests
CORS_PREFLIGHT_MAX_AGE = 86400

# CSRF trusted origins must include scheme + host[:port]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://192.168.56.1:3000",
    "http://192.168.0.126:3000",
    "http://10.0.0.5:3000",
    "http://10.0.0.6:3000",
    "http://10.0.0.14:3000",
    # Render frontend (production)
    "https://transportista-frontend.onrender.com",
]

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Configuración de base de datos para desarrollo (SQLite)
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

# Configuración para producción (PostgreSQL en Render)
DATABASES = {
    "default": dj_database_url.parse(os.environ.get("DATABASE_URL"))
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-mx"

TIME_ZONE = "America/Mexico_City"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
_STATIC_DIR = BASE_DIR / "static"
STATICFILES_DIRS = [_STATIC_DIR] if _STATIC_DIR.exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"  # Required for collectstatic on Render
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Frontend URL configuration
# En desarrollo se genera automáticamente
# En producción debes configurar esta URL
FRONTEND_URL = os.environ.get('FRONTEND_URL') or ("http://localhost:3000" if DEBUG else None)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Ejemplos de configuración para producción:
# FRONTEND_URL = 'https://tu-frontend.com'  # Para dominios separados
# FRONTEND_URL = 'https://tu-dominio.com'   # Para mismo dominio
# FRONTEND_URL = None                       # Para generar automáticamente en desarrollo

# =====================
# Cloudinary Integration
# =====================
# Apps
try:
    INSTALLED_APPS
except NameError:
    INSTALLED_APPS = []

for app in ['cloudinary', 'cloudinary_storage']:
    if app not in INSTALLED_APPS:
        INSTALLED_APPS.append(app)

# Credentials only from environment (no hardcoded defaults)
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET')
if not DEBUG and not all([CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET]):
    raise RuntimeError("Cloudinary credentials must be set in production")

# Provide settings dict expected by cloudinary_storage at import time
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME or ('dw2rmznvx' if DEBUG else None),
    'API_KEY': CLOUDINARY_API_KEY or ('513368538693322' if DEBUG else None),
    'API_SECRET': CLOUDINARY_API_SECRET or ('jorrUdo4ql2lMAmbSHNcOoz5hhU' if DEBUG else None),
    'SECURE': True,
    # Ensure media uploads are public and delivered via image/upload
    'UPLOAD_OPTIONS': {
        'type': 'upload',
        'access_mode': 'public',
        'use_filename': True,
        'unique_filename': False,
        'overwrite': True,
    },
    # Make raw uploads publicly deliverable (avoid authenticated/raw requiring signed URLs)
    'RAW_UPLOAD_OPTIONS': {
        'resource_type': 'raw',
        'type': 'upload',
        'overwrite': True,
    },
}

# Configuración de email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'grupointegraordenes@gmail.com'
EMAIL_HOST_PASSWORD = 'qwrc bwag paip zoue'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 20

# Always use Cloudinary for media storage (serve via image/upload)
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Image optimization config
IMAGE_OPTIMIZATION_CONFIG = {
    'MAX_SIZE_KB': 50,  # Reducido de 100KB a 50KB
    'MAX_DIMENSION': 800,  # Reducido de 1000px
    'DEFAULT_QUALITY': 75,  # Reducido de 85
    'MAX_ATTEMPTS': 8,
    'FOLDERS': {
        'ORDENES': 'ordenes_servicio',
        'FIRMAS': 'firmas',
        'INCIDENCIAS': 'incidencias',
    },
}

# Cloudinary upload default params
CLOUDINARY_UPLOAD_PARAMS = {
    'quality': 'auto:good',  # Cambiado de 'auto:best' a 'auto:good'
    'fetch_format': 'auto',
    'flags': 'progressive',
    'width': 800,  # Reducido de 1000px
    'crop': 'limit',
    'dpr': 'auto',
    'resource_type': 'auto',
}

# Security behind proxy (Render) and secure cookies in production
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Allow cross-site cookies from separate frontend domain
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"
    SECURE_HSTS_SECONDS = 60 * 60 * 24
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True