# Generated by Django 5.1.4 on 2026-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Grupo Intrax', max_length=120)),
                ('logo_url', models.TextField(blank=True, default='')),
                ('logo_public_id', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca del sistema',
                'verbose_name_plural': 'Marca del sistema',
            },
        ),
    ]
