# Generated by Django 5.1.4 on 2026-05-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_cliente_thumbnail_len'),
        ('productos', '0005_rename_productos_p_producto_1ef977_idx_productos_p_product_51c25a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_trabajo',
            field=models.ManyToManyField(blank=True, related_name='cotizaciones', to='productos.servicio'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='medio_contacto',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('BNI', 'BNI'), ('REFERIDO', 'Referido'), ('WEB', 'Web'), ('TIENDA_ONLINE', 'Tienda Online'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'Tiktok'), ('GOOGLE_MAPS', 'Google Maps'), ('YOUTUBE', 'Youtube'), ('TIENDA_FISICA', 'Tienda Fisica')], default='', max_length=30),
        ),
    ]
