# Generated by Django 5.1.4 on 2026-02-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0002_cotizacion_actualizado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="descuento_cliente_pct",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
