# Generated by Django 5.1.4 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0003_cotizacion_descuento_cliente_pct"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="medio_contacto",
            field=models.CharField(blank=True, choices=[("BNI", "BNI"), ("REFERIDO", "Referido"), ("WEB", "Web"), ("TIENDA_ONLINE", "Tienda Online"), ("FACEBOOK", "Facebook"), ("INSTAGRAM", "Instagram"), ("TIKTOK", "Tiktok"), ("GOOGLE_MAPS", "Google Maps"), ("YOUTUBE", "Youtube"), ("TIENDA_FISICA", "Tienda Fisica"), ("OTRO", "Otro")], default="", max_length=30),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="status",
            field=models.CharField(blank=True, choices=[("AUTORIZADA", "Autorizada"), ("PENDIENTE", "Pendiente"), ("CANCELADA", "Cancelada")], default="PENDIENTE", max_length=20),
        ),
    ]
