# Generated by Django 5.x - Remove Producto FK; use producto_externo_id (e.g. SYSCOM id)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones", "0004_cotizacion_medio_contacto_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacionitem",
            name="producto_externo_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RemoveField(
            model_name="cotizacionitem",
            name="producto_id",
        ),
    ]
