# Generated by Django 5.2.17 on 2026-09-09 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_alter_cotizacionitem_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='anticipo_pct',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=5, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
