# Generated by Django 5.1.4 on 2026-09-21 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_cotizacion_anticipo_pct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='enviado_comentario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
