# Generated by Django 5.1.4 on 2026-10-07 18:27

import apps.contratos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0007_backfill_clientedireccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('folio', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('cliente_tipo_persona', models.CharField(choices=[('moral', 'Persona moral'), ('fisica', 'Persona física')], default='moral', max_length=10)),
                ('cliente_razon_social', models.CharField(max_length=255)),
                ('cliente_rfc', models.CharField(blank=True, default='', max_length=13)),
                ('cliente_regimen_fiscal', models.CharField(blank=True, default='', max_length=120)),
                ('cliente_domicilio_fiscal', models.TextField(blank=True, default='')),
                ('cliente_representante', models.CharField(blank=True, default='', max_length=255)),
                ('cliente_clave_elector', models.CharField(blank=True, default='', max_length=18)),
                ('cliente_curp', models.CharField(blank=True, default='', max_length=18)),
                ('cliente_correo', models.EmailField(blank=True, default='', max_length=254)),
                ('domicilio_instalacion', models.TextField(blank=True, default='')),
                ('plan_mbps', models.PositiveIntegerField(default=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vigencia_meses', models.PositiveSmallIntegerField(default=36)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('ciudad_firma', models.CharField(blank=True, default='Manzanillo, Colima', max_length=120)),
                ('prestador_datos', models.JSONField(blank=True, default=apps.contratos.models._prestador_default)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado a firma'), ('firmado_cliente', 'Firmado por el cliente'), ('firmado_prestador', 'Firmado por el prestador'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20)),
                ('documento_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('firma_prestador_png', models.TextField(blank=True, default='')),
                ('firma_prestador_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('firmado_prestador_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('firmado_prestador_at', models.DateTimeField(blank=True, null=True)),
                ('firmado_prestador_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('firma_cliente_png', models.TextField(blank=True, default='')),
                ('firma_cliente_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('firma_cliente_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('firmado_cliente_at', models.DateTimeField(blank=True, null=True)),
                ('firmado_cliente_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('firmado_cliente_user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('firmado_cliente_correo', models.EmailField(blank=True, default='', max_length=254)),
                ('pdf_sellado', models.BinaryField(blank=True, null=True)),
                ('pdf_sellado_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('sellado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL)),
                ('firmado_prestador_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_firmados_prestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-idx'],
            },
        ),
        migrations.CreateModel(
            name='ContratoEnlaceFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('correo_destino', models.EmailField(max_length=254)),
                ('documento_sha256', models.CharField(max_length=64)),
                ('expira_at', models.DateTimeField()),
                ('revocado_at', models.DateTimeField(blank=True, null=True)),
                ('usado_at', models.DateTimeField(blank=True, null=True)),
                ('otp_hash', models.CharField(blank=True, default='', max_length=64)),
                ('otp_expira_at', models.DateTimeField(blank=True, null=True)),
                ('otp_intentos', models.PositiveSmallIntegerField(default=0)),
                ('otp_enviados', models.PositiveSmallIntegerField(default=0)),
                ('otp_ultimo_envio_at', models.DateTimeField(blank=True, null=True)),
                ('verificado_at', models.DateTimeField(blank=True, null=True)),
                ('sesion_hash', models.CharField(blank=True, default='', max_length=64)),
                ('sesion_expira_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='contratos.contrato')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_enlaces_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enlace de firma',
                'verbose_name_plural': 'Enlaces de firma',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContratoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creado', 'Contrato creado'), ('editado', 'Contrato editado'), ('enviado', 'Enlace de firma generado'), ('enlace_correo', 'Enlace enviado por correo'), ('revocado', 'Enlace revocado'), ('link_abierto', 'Enlace abierto'), ('otp_enviado', 'Código enviado'), ('otp_fallido', 'Código incorrecto'), ('otp_bloqueado', 'Enlace bloqueado por intentos'), ('otp_verificado', 'Identidad verificada'), ('documento_visto', 'Documento consultado'), ('firmado_cliente', 'Firmado por el cliente'), ('firmado_prestador', 'Firmado por el prestador'), ('sellado', 'Documento sellado'), ('cancelado', 'Contrato cancelado')], max_length=30)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='contratos.contrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de contrato',
                'verbose_name_plural': 'Eventos de contrato',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado'], name='contratos_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['cliente_razon_social'], name='contratos_cliente_rs_idx'),
        ),
    ]
