# Generated by Django 5.1.4 on 2026-01-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(db_index=True, unique=True)),
                ('no_cliente', models.IntegerField(blank=True, null=True)),
                ('fecha_lead', models.DateField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, default='', max_length=25)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('canal_contacto', models.CharField(blank=True, default='', max_length=100)),
                ('linea_sistema', models.CharField(blank=True, default='', max_length=120)),
                ('producto_servicio', models.CharField(blank=True, default='', max_length=200)),
                ('no_cotizacion', models.CharField(blank=True, default='', max_length=100)),
                ('levantamiento', models.CharField(blank=True, default='', max_length=150)),
                ('monto_cotizado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=80)),
                ('probabilidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, default='', max_length=150)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('monto_vendido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('motivo_perdida', models.TextField(blank=True, default='')),
                ('proxima_accion', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_proxima_accion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KPI de Ventas',
                'verbose_name_plural': 'KPI de Ventas',
                'ordering': ['idx'],
                'indexes': [models.Index(fields=['idx'], name='kpis_kpiven_idx_8d68e3_idx'), models.Index(fields=['nombre_cliente'], name='kpis_kpiven_nombre__77b816_idx'), models.Index(fields=['fecha_lead'], name='kpis_kpiven_fecha_l_023ef9_idx'), models.Index(fields=['status'], name='kpis_kpiven_status_32d989_idx')],
            },
        ),
    ]
