# Generated by Django 5.1.4 on 2026-04-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escritorio', '0002_add_estado_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['estado', 'orden', '-fecha_creacion'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
    ]
