# Generated by Django 5.1.4 on 2026-01-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(db_index=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, default='')),
                ('telefono', models.CharField(blank=True, default='', max_length=100)),
                ('rfc', models.CharField(blank=True, default='', max_length=50)),
                ('curp', models.CharField(blank=True, default='', max_length=100)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('calle', models.CharField(blank=True, default='', max_length=255)),
                ('numero_exterior', models.CharField(blank=True, default='', max_length=100)),
                ('interior', models.CharField(blank=True, default='', max_length=100)),
                ('colonia', models.CharField(blank=True, default='', max_length=255)),
                ('localidad', models.CharField(blank=True, default='', max_length=255)),
                ('municipio', models.CharField(blank=True, default='', max_length=255)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=50)),
                ('ciudad', models.CharField(blank=True, default='', max_length=255)),
                ('pais', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(blank=True, default='', max_length=255)),
                ('aplica_retenciones', models.BooleanField(default=False)),
                ('desglosar_ieps', models.BooleanField(default=False)),
                ('numero_precio', models.CharField(blank=True, default='1', max_length=50)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dias_credito', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa'), ('PERSONA_FISICA', 'Persona Física'), ('PROVEEDOR', 'Proveedor')], default='EMPRESA', help_text='Identificador de tipo de cliente/entidad', max_length=50)),
                ('is_prospecto', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, default='')),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('portal_web', models.CharField(blank=True, default='', max_length=255)),
                ('nombre_facturacion', models.CharField(blank=True, default='', max_length=255)),
                ('numero_facturacion', models.CharField(blank=True, default='', max_length=100)),
                ('domicilio_facturacion', models.TextField(blank=True, default='')),
                ('calle_envio', models.CharField(blank=True, default='', max_length=255)),
                ('numero_envio', models.CharField(blank=True, default='', max_length=100)),
                ('colonia_envio', models.CharField(blank=True, default='', max_length=255)),
                ('codigo_postal_envio', models.CharField(blank=True, default='', max_length=50)),
                ('pais_envio', models.CharField(blank=True, default='', max_length=255)),
                ('estado_envio', models.CharField(blank=True, default='', max_length=255)),
                ('ciudad_envio', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['idx'],
            },
        ),
        migrations.CreateModel(
            name='ClienteContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('area_puesto', models.CharField(blank=True, default='', max_length=150)),
                ('celular', models.CharField(blank=True, default='', max_length=25)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('is_principal', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Cliente',
                'ordering': ['-is_principal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='')),
                ('public_id', models.CharField(blank=True, default='', max_length=255)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Documento de Cliente',
                'verbose_name_plural': 'Documentos de Cliente',
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['idx'], name='clientes_cl_idx_04b478_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='clientes_cl_nombre_c231de_idx'),
        ),
        migrations.AddIndex(
            model_name='clientecontacto',
            index=models.Index(fields=['cliente'], name='clientes_cl_cliente_08bdf6_idx'),
        ),
        migrations.AddIndex(
            model_name='clientecontacto',
            index=models.Index(fields=['is_principal'], name='clientes_cl_is_prin_ca1baa_idx'),
        ),
    ]
