# Generated by Django 5.1.4 on 2026-01-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        # Las operaciones de RenameIndex se eliminaron para evitar errores en Render
        # ya que los índices originales "clientes_cli_..." no se encontraban en la base de datos de producción.
        # Los nombres definitivos "clientes_cl_..." se integraron directamente en 0001_initial.py.
    ]
