# Generated by Django 5.1.4 on 2026-01-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_calle_alter_cliente_calle_envio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_prospecto',
            field=models.BooleanField(default=False),
        ),
    ]
