# Generated by Django 5.1.4 on 2026-09-01 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_formulario_simplificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUsernameSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia username portal cliente',
                'verbose_name_plural': 'Secuencia username portal cliente',
            },
        ),
        migrations.CreateModel(
            name='ClientePortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_username', models.CharField(db_index=True, max_length=32, unique=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('temp_password_issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('pending_review', 'Pendiente de revisión'), ('suspended', 'Suspendido')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_accounts', to='clientes.cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_portal_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta portal cliente',
                'verbose_name_plural': 'Cuentas portal cliente',
            },
        ),
        migrations.CreateModel(
            name='ClienteRegistroSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=25)),
                ('razon_social', models.CharField(blank=True, default='', max_length=255)),
                ('rfc', models.CharField(blank=True, default='', max_length=50)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=50)),
                ('acepto_privacidad', models.BooleanField(default=False)),
                ('dedup_result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('auto_approved', 'Aprobada automáticamente')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_solicitudes', to='clientes.cliente')),
                ('portal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='clientes.clienteportalaccount')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud registro portal cliente',
                'verbose_name_plural': 'Solicitudes registro portal cliente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='clienteportalaccount',
            constraint=models.UniqueConstraint(fields=('cliente', 'user'), name='uniq_portal_user_cliente'),
        ),
    ]
