# Generated by Django 5.1.4 on 2026-09-11 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_portal_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(blank=True, default='', max_length=100)),
                ('direccion', models.TextField(blank=True, default='')),
                ('calle', models.CharField(blank=True, default='', max_length=255)),
                ('numero_exterior', models.CharField(blank=True, default='', max_length=100)),
                ('interior', models.CharField(blank=True, default='', max_length=100)),
                ('colonia', models.CharField(blank=True, default='', max_length=255)),
                ('localidad', models.CharField(blank=True, default='', max_length=255)),
                ('municipio', models.CharField(blank=True, default='', max_length=255)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=50)),
                ('ciudad', models.CharField(blank=True, default='', max_length=255)),
                ('pais', models.CharField(blank=True, default='México', max_length=255)),
                ('estado', models.CharField(blank=True, default='', max_length=255)),
                ('is_principal', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Dirección de Cliente',
                'verbose_name_plural': 'Direcciones de Cliente',
                'ordering': ['-is_principal', 'id'],
                'indexes': [models.Index(fields=['cliente'], name='clientes_cl_cliente_adb596_idx'), models.Index(fields=['is_principal'], name='clientes_cl_is_prin_1b5bc4_idx')],
            },
        ),
    ]
