# Generated by Django 5.1.4 on 2026-07-27 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_formulario_simplificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('folio', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('en_proceso', 'En proceso'), ('pausado', 'Pausado'), ('cerrado', 'Cerrado')], default='en_proceso', max_length=20)),
                ('motivo_pausa', models.TextField(blank=True, default='')),
                ('tipo_trabajo_id', models.IntegerField(blank=True, null=True)),
                ('tipo_trabajo_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_autorizacion', models.DateField(blank=True, null=True)),
                ('fechas_inicio', models.JSONField(blank=True, default=list)),
                ('hora_llegada', models.CharField(blank=True, default='', max_length=10)),
                ('hora_salida', models.CharField(blank=True, default='', max_length=10)),
                ('tecnico_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('auxiliar_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('vehiculo_asignado', models.TextField(blank=True, default='')),
                ('herramientas_generales', models.TextField(blank=True, default='')),
                ('cotizaciones', models.JSONField(blank=True, default=list)),
                ('cotizacion_adicional', models.JSONField(blank=True, null=True)),
                ('equipos', models.JSONField(blank=True, default=list)),
                ('notas_por_dia', models.JSONField(blank=True, default=list)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=0)),
                ('incidencias', models.TextField(blank=True, default='')),
                ('requerimientos_adicionales', models.TextField(blank=True, default='')),
                ('requiere_presupuesto_adicional', models.BooleanField(default=False)),
                ('evidencias_urls', models.JSONField(blank=True, default=list)),
                ('firma_cliente_url', models.TextField(blank=True, default='')),
                ('firma_tecnico_url', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auxiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_como_auxiliar', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_como_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-idx'],
                'indexes': [models.Index(fields=['idx'], name='operacion_p_idx_560cab_idx'), models.Index(fields=['status'], name='operacion_p_status_14064a_idx'), models.Index(fields=['cliente_nombre'], name='operacion_p_cliente_361f5c_idx')],
            },
        ),
    ]
