# Generated by Django 5.1.4 on 2026-07-30 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_proyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoInstalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dibujo_url', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecto_instalaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones', to='operacion.proyecto')),
            ],
            options={
                'verbose_name': 'Instalación de proyecto',
                'verbose_name_plural': 'Instalaciones de proyecto',
                'ordering': ['-idx', '-id'],
                'indexes': [models.Index(fields=['idx'], name='operacion_p_idx_74aaa3_idx'), models.Index(fields=['proyecto'], name='operacion_p_proyect_124984_idx')],
            },
        ),
    ]
