# Generated by Django 5.1.4 on 2026-08-21 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0008_polizamantenimiento_intervalo_meses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('folio', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('fecha_servicio', models.DateField()),
                ('tecnico_nombre', models.CharField(max_length=255)),
                ('foto_orden_url', models.TextField(blank=True, default='')),
                ('secciones', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_mantenimiento_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de mantenimiento',
                'verbose_name_plural': 'Reportes de mantenimiento',
                'ordering': ['-idx'],
                'indexes': [models.Index(fields=['idx'], name='operacion_rm_idx_idx'), models.Index(fields=['folio'], name='operacion_rm_folio_idx'), models.Index(fields=['tecnico_nombre'], name='operacion_rm_tecnico_idx')],
            },
        ),
    ]
