# Generated by Django 5.1.4 on 2026-08-21 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0009_reporte_mantenimiento'),
        ('ordenes', '0013_orden_list_fecha_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemantenimiento',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_mantenimiento', to='ordenes.orden'),
        ),
        migrations.AddField(
            model_name='reportemantenimiento',
            name='orden_cliente',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reportemantenimiento',
            name='orden_folio',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
