# Generated by Django 5.1.4 on 2026-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0012_drop_orphan_cotizaciones_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='status',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('pausado', 'Pausado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20),
        ),
    ]
