# Generated by Django 5.1.4 on 2026-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0014_status_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='monitoreo',
            field=models.BooleanField(default=False),
        ),
    ]
