# Generated by Django 5.1.4 on 2026-09-18 17:51

from django.db import migrations, models


def reset_monitoreo_no_elegido(apps, schema_editor):
    """
    Antes de esta migración `monitoreo` era un booleano normal con
    `default=False`: todo proyecto ya existente quedó en `False` por ese
    default, sin que nadie lo haya elegido de verdad en la UI (la UI para
    elegirlo no existía todavía). Al volverse un tercer estado real, esos
    `False` heredados se regresan a `NULL` ("aún no elegido") para no simular
    una elección de "No" que jamás ocurrió.
    """
    Proyecto = apps.get_model('operacion', 'Proyecto')
    Proyecto.objects.filter(monitoreo=False).update(monitoreo=None)


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0015_proyecto_monitoreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='monitoreo',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(reset_monitoreo_no_elegido, migrations.RunPython.noop),
    ]
