# Generated by Django 5.2.17 on 2026-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0016_alter_proyecto_monitoreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='polizamantenimiento',
            name='fecha4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
