# Generated by Django 5.2.17 on 2026-09-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0018_liquidado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='status',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('pausado', 'Pausado'), ('saldo_pendiente', 'Saldo pendiente'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20),
        ),
    ]
