# Generated by Django 5.2.17 on 2026-09-28 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0019_status_saldo_pendiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoReasignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('orden', 'Orden de trabajo'), ('proyecto', 'Proyecto')], max_length=10)),
                ('objeto_id', models.PositiveIntegerField()),
                ('folio', models.CharField(blank=True, default='', max_length=50)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('accion', models.CharField(choices=[('reasignar', 'Reasignar'), ('deshacer', 'Deshacer')], default='reasignar', max_length=10)),
                ('desde_id', models.IntegerField(blank=True, null=True)),
                ('desde_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('hacia_id', models.IntegerField(blank=True, null=True)),
                ('hacia_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('creado_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_reasignaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_at', '-id'],
                'indexes': [models.Index(fields=['tipo', 'objeto_id'], name='operacion_eqr_obj_idx')],
            },
        ),
    ]
