# Generated by Django 5.2.17 on 2026-09-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0020_equipo_reasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiporeasignacion',
            name='desde_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equiporeasignacion',
            name='hacia_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
