# Generated by Django 5.1.4 on 2026-10-01 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0021_equipo_reasignacion_fechas'),
        ('ordenes', '0024_status_saldo_pendiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemantenimiento',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_mantenimiento', to='operacion.proyecto'),
        ),
        migrations.AddConstraint(
            model_name='reportemantenimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('proyecto__isnull', False)), fields=('proyecto',), name='operacion_rm_proyecto_unico'),
        ),
    ]
