# Generated by Django 5.1.4 on 2026-01-10 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(db_index=True, unique=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=200)),
                ('unidad', models.CharField(blank=True, default='', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('modelo', models.CharField(blank=True, default='', max_length=200)),
                ('codigo_fabrica', models.CharField(blank=True, default='', max_length=200)),
                ('proveedor', models.CharField(blank=True, default='', max_length=200)),
                ('fabricante_marca', models.CharField(blank=True, default='', max_length=200)),
                ('punto_pedido', models.IntegerField(blank=True, null=True)),
                ('stock_inicial', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, default='', max_length=200)),
                ('codigo_sat', models.CharField(blank=True, default='', max_length=200)),
                ('unidad_sat', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['idx'],
                'indexes': [models.Index(fields=['idx'], name='productos_p_idx_9e08ef_idx'), models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='')),
                ('public_id', models.CharField(blank=True, default='', max_length=255)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Documento de Producto',
                'verbose_name_plural': 'Documentos de Producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='')),
                ('public_id', models.CharField(blank=True, default='', max_length=255)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
            },
        ),
    ]
