# Generated by Django 5.1.4 on 2026-04-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicio',
            new_name='productos_s_idx_c28d22_idx',
            old_name='productos_se_idx_b2d0f8_idx',
        ),
        migrations.RenameIndex(
            model_name='servicio',
            new_name='productos_s_nombre_6cb91a_idx',
            old_name='productos_se_nombre_3eb2ae_idx',
        ),
        migrations.RenameIndex(
            model_name='servicio',
            new_name='productos_s_activo_f1b54a_idx',
            old_name='productos_se_activo_7f9e9f_idx',
        ),
        migrations.RenameIndex(
            model_name='servicio',
            new_name='productos_s_categor_41a800_idx',
            old_name='productos_se_categor_83f621_idx',
        ),
    ]
