# Generated by Django 5.1.4 on 2026-01-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producto',
            new_name='productos_p_idx_9e08ef_idx',
            old_name='productos_pr_idx_2dd1d7_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='productos_p_nombre_456643_idx',
            old_name='productos_pr_nombre_8cc3e4_idx',
        ),
    ]
