# Generated by Django 5.1.4 on 2026-02-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_productos_pr_idx_2dd1d7_idx_productos_p_idx_9e08ef_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='unidad_sat',
        ),
        migrations.AddField(
            model_name='producto',
            name='iva_pct',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='ProductoDocumento',
        ),
    ]
