# Generated by Django 5.1.4 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_unidad_sat_producto_iva_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(db_index=True, unique=True)),
                ('nombre', models.CharField(default='', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['idx'],
            },
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['idx'], name='productos_se_idx_b2d0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['nombre'], name='productos_se_nombre_3eb2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['activo'], name='productos_se_activo_7f9e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['categoria'], name='productos_se_categor_83f621_idx'),
        ),
    ]
