# Generated by Django 5.1.4 on 2026-05-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_drop_legacy_producto_table'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productomanual',
            new_name='productos_p_product_51c25a_idx',
            old_name='productos_p_producto_1ef977_idx',
        ),
        migrations.RenameIndex(
            model_name='productomanual',
            new_name='productos_p_marca_7771ce_idx',
            old_name='productos_p_marca_68e0b2_idx',
        ),
        migrations.RenameIndex(
            model_name='productomanual',
            new_name='productos_p_modelo_c768ae_idx',
            old_name='productos_p_modelo_2bbdbc_idx',
        ),
        migrations.RenameIndex(
            model_name='productomanual',
            new_name='productos_p_fuente_f52cee_idx',
            old_name='productos_p_fuente_44a2fa_idx',
        ),
        migrations.RenameIndex(
            model_name='productomanual',
            new_name='productos_p_activo_7bc242_idx',
            old_name='productos_p_activo_5e7354_idx',
        ),
    ]
