# Generated by Django 5.2.17 on 2026-10-09 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_backfill_clientedireccion'),
        ('productos', '0008_productomanual_sat_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomanual',
            name='proveedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PROVEEDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_manuales', to='clientes.cliente'),
        ),
    ]
