# Generated by Django 5.1.4 on 2026-08-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneDriveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='default', max_length=32, unique=True)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('refresh_token_encrypted', models.TextField(blank=True, default='')),
                ('root_item_id', models.CharField(blank=True, default='', max_length=255)),
                ('root_name', models.CharField(blank=True, default='', max_length=255)),
                ('pending_state', models.CharField(blank=True, default='', max_length=128)),
                ('pending_redirect_uri', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conexión OneDrive',
                'verbose_name_plural': 'Conexiones OneDrive',
            },
        ),
    ]
