# Generated by Django 5.1.4 on 2026-08-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='imagen_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
