# Generated by Django 5.1.4 on 2026-08-05 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventarioitem_imagen_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('syscom', 'SYSCOM'), ('tvc', 'TVC')], max_length=20)),
                ('folio', models.CharField(max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_importaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación de factura',
                'verbose_name_plural': 'Importaciones de factura',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('proveedor', 'folio'), name='inventario_importacion_proveedor_folio_uniq')],
            },
        ),
    ]
