# Generated by Django 5.1.4 on 2026-08-07 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_formulario_simplificado'),
        ('inventario', '0003_inventarioimportacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='folio_factura',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='proveedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'PROVEEDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_items', to='clientes.cliente'),
        ),
    ]
