# Generated by Django 5.1.4 on 2026-08-13 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_inventarioitem_seccion'),
        ('ordenes', '0012_orden_equipos_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariomovimiento',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='ordenes.orden'),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='orden_linea_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
