# Generated by Django 5.2.17 on 2026-09-24 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_inventariomovimiento_orden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(choices=[('syscom', 'SYSCOM'), ('tvc', 'TVC')], max_length=20)),
                ('folio', models.CharField(db_index=True, max_length=64)),
                ('ref_externa', models.CharField(blank=True, default='', max_length=120)),
                ('modelo', models.CharField(blank=True, default='', max_length=120)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('marca', models.CharField(blank=True, default='', max_length=120)),
                ('imagen_url', models.URLField(blank=True, default='', max_length=500)),
                ('caracteristicas', models.TextField(blank=True, default='')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_facturada', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendientes', to='inventario.inventarioimportacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_pendientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto en espera',
                'verbose_name_plural': 'Productos en espera',
                'ordering': ['-creado_en', 'id'],
            },
        ),
    ]
