# Generated by Django 5.2.17 on 2026-09-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_inventariopendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='precio_mercado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='precio_mercado_actualizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='precio_mercado_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('exhibicion', 'Exhibición'), ('almacen', 'Almacén')], db_index=True, default='', max_length=20),
        ),
    ]
