# Generated by Django 5.2.17 on 2026-10-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_reiniciar_precio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='sin_proveedor',
            field=models.BooleanField(default=False),
        ),
    ]
