# Generated by Django 5.1.4 on 2026-01-29 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_rename_clientes_cli_idx_5b2d08_idx_clientes_cl_idx_04b478_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=15, null=True)),
                ('problematica', models.TextField(blank=True, null=True)),
                ('servicios_realizados', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('comentario_tecnico', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('hora_termino', models.TimeField(blank=True, null=True)),
                ('nombre_encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('fotos_urls', models.JSONField(blank=True, default=list)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('firma_encargado_url', models.TextField(blank=True, null=True)),
                ('firma_cliente_url', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['idx'],
                'indexes': [models.Index(fields=['idx'], name='ordenes_ord_idx_6e443d_idx'), models.Index(fields=['cliente'], name='ordenes_ord_cliente_2cfe54_idx'), models.Index(fields=['fecha_inicio'], name='ordenes_ord_fecha_i_ed9bd0_idx')],
            },
        ),
    ]
