# Generated by Django 5.2.6 on 2025-12-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
