# Generated by Django 5.2.6 on 2025-12-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_orden_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='firma_cliente_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='firma_encargado_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
