# Generated by Django 5.1.4 on 2026-04-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_reportesemanal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportesemanal',
            new_name='ordenes_rep_tecnico_d600b3_idx',
            old_name='ordenes_rep_tecnic_2e75ce_idx',
        ),
        migrations.RenameIndex(
            model_name='reportesemanal',
            new_name='ordenes_rep_fecha_c_5daca3_idx',
            old_name='ordenes_rep_fecha_c09f45_idx',
        ),
    ]
