# Generated by Django 5.1.4 on 2026-08-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0011_orden_status_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='equipos_inventario',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
