# Generated by Django 5.1.4 on 2026-08-13 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_formulario_simplificado'),
        ('ordenes', '0012_orden_equipos_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['fecha_creacion'], name='ordenes_ord_fecha_c_4df55e_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['-fecha_inicio', '-fecha_creacion', '-id'], name='ordenes_ord_fecha_i_60b8ba_idx'),
        ),
    ]
