# Generated by Django 5.1.4 on 2026-09-01 18:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_orden_status_pausado_motivo_pausa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='ordenes.orden')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación de orden',
                'verbose_name_plural': 'Calificaciones de órdenes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['tecnico', 'fecha_creacion'], name='ordenes_ord_tecnico_9aa1c7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('estrellas__gte', 1), ('estrellas__lte', 5)), name='calificacion_estrellas_1_a_5')],
            },
        ),
    ]
