# Generated by Django 5.1.4 on 2026-09-07 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_portal_cliente'),
        ('ordenes', '0016_orden_actualizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='en_pool',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='liberada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='liberada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_liberadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orden',
            name='prioridad_pool',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='tomada_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='tomada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_tomadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['en_pool', 'prioridad_pool'], name='ordenes_ord_en_pool_e80336_idx'),
        ),
    ]
