# Generated by Django 5.1.4 on 2026-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_squashed_0018_backfill_contacto_desde_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pausado', 'Pausado'), ('resuelto', 'Resuelto'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
