# Generated by Django 5.1.4 on 2026-09-14

from django.db import migrations
from django.db.models import Case, F, Q, When
from django.db.models.functions import Coalesce


def backfill_status_changed_by(apps, schema_editor):
    """Filas con fecha de status y sin autor: creador (pendiente) o último editor."""
    Orden = apps.get_model("ordenes", "Orden")
    Orden.objects.filter(status_changed_by_id__isnull=True).update(
        status_changed_by_id=Case(
            When(Q(status__iexact="pendiente"), then=F("creado_por_id")),
            default=Coalesce("actualizado_por_id", "creado_por_id"),
        )
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0020_status_changed_by"),
    ]

    operations = [
        migrations.RunPython(backfill_status_changed_by, noop_reverse),
    ]
