# Generated by Django 5.1.4 on 2026-09-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_backfill_clientedireccion"),
        ("ordenes", "0021_backfill_status_changed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="cliente_direccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordenes",
                to="clientes.clientedireccion",
            ),
        ),
    ]
