# Generated by Django 5.2.17 on 2026-09-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0022_orden_cliente_direccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='liquidado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='liquidado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='liquidado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_liquidadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
